apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-4it5dh
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-4it5dh
  namespace: my-nginx-4it5dh
  labels:
    name: nginx-4it5dh
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-4it5dh
  template:
    metadata:
      namespace: my-nginx-4it5dh
      labels:
        name: nginx-4it5dh
    spec:
      containers:
      - name: nginx-4it5dh
        image: nginx
        ports:
        - containerPort: 80

